### PR TITLE
'mc' unit tests

### PR DESCRIPTION
**Pull request by bpuchala**
Adding more 'mc' unit tests

### CODE REVIEW

**Comment by Terry-Weymouth** [comment]
Brian, could you please pull the current sprint and merge it into your code on your repository.
Then push to your branch on your repository. That will update the Pull Request. 
And, my guess is, it will pass the tests on travis (I disabled the troublesome tests).

**Comment by bpuchala** [comment]
This doesn't need to be merged yet.  I'll change the name to add [WIP] for "work-in-progress" and ping you when it's ready.

**Comment by bpuchala** [comment]
This is probably a good place to merge.

**Comment by Terry-Weymouth** [comment]
Agree. Merged.

**Pull request merged**
